version: '3'
services: 
    nginx:
        image: piteron/nginx
        networks:
            - back
        ports: 
            - "80:80"
    idd-docker:
        image: piteron/idd-docker:0.0.1-SNAPSHOT
        networks:
            - back
        ports: 
            - "8081:8080"
    rest-repository:
        image: piteron/rest-repository:0.0.1-SNAPSHOT
        networks:
            - back
        depends_on: 
            - elasticsearch
        ports: 
            - "8082:8080"
    elasticsearch:
        image: elasticsearch:2-alpine
        networks: 
            - back
    logstash:
        image: docker.elastic.co/logstash/logstash:5.2.1
        networks: 
            - back
    kibana:
        image: docker.elastic.co/kibana/kibana:5.2.1
        networks: 
            - back
        ports: 
            - "5601:5601"
networks: 
    back: