version: '3'
services: 
    nginx:
        image: piteron/nginx
        networks:
            - back
        ports: 
            - "80:80"
    idd-docker:
        image: piteron/idd-docker:0.0.1-SNAPSHOT
        networks:
            - back
        ports: 
            - "8081:8080"
    rest-repository:
        image: piteron/rest-repository:0.0.1-SNAPSHOT
        networks:
            - back
        depends_on: 
            - elasticsearch
        ports: 
            - "8082:8080"
    elasticsearch:
        image: elasticsearch:2-alpine
        networks: 
            - back
        ports: 
            - "9200:9200"
            - "9300:9300"
    logstash:
        image: piteron/logstash:2-alpine
        networks: 
            - back
        ports: 
            - "5000:5000"
    logspout-logstash:
        image: piteron/logspout-logstash
        depends_on: 
            - logstash
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        environment: 
            - ROUTE_URIS=logstash+tcp://logstash:5000
        networks: 
            - back
    kibana:
        image: kibana:4
        networks: 
            - back
        ports: 
            - "5601:5601"
networks: 
    back: